services:
  main:
    build: .
    container_name: lss-main
    ports:
      - 5000:5000
    volumes:
      - ~/.aws:/root/.aws
      - data:/data
    environment:
      - SQLALCHEMY_URL=sqlite:///data/lss.db
      - IAM_ROLE=${IAM_ROLE}
    develop:
      watch:
        - action: sync
          path: ./lss
          target: /lss
    restart: always
volumes:
  data:
