services:
  main:
    build: .
    container_name: lss
    ports:
      - 5000:5000
    volumes:
      - ~/.aws:/root/.aws
      - ./config:/config
      - data:/data
    environment:
      - SQLALCHEMY_URL=${SQLALCHEMY_URL}
      - IAM_ROLE=${IAM_ROLE}
    develop:
      watch:
        - action: sync
          path: ./lss
          target: /lss
    restart: always
volumes:
  data:
