services:
  main:
    build: .
    container_name: lessrss
    ports:
      - 5000:5000
    volumes:
      - ~/.aws:/root/.aws
      - data:/data
      - ./config:/config
      - ./models:/models
    environment:
      - SQLALCHEMY_URL=${SQLALCHEMY_URL}
      - IAM_ROLE=${IAM_ROLE}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - ./src/app/__pycache__/
            - ./src/.venv/
    restart: always
volumes:
  data:
  config:
