---
host: https://www.yoursite.com
quorom: 1
feeds:
  - url: https://feeds.bloomberg.com/markets/news.rss
    directory: bloomberg/markets
  - url: https://news.ycombinator.com/rss
    directory: hacker_news
  - url: https://techcrunch.com/feed
    directory: techcrunch
    quorom: 3
classifiers:
  tfidf:
    weight: 1
    classifier_active: true
  distilbert:
    weight: 2
    classifier_active: false
