---
host: "http://localhost:5000"
quorom: 2
feeds:
  - url: "https://news.ycombinator.com/rss"
    directory: hacker_news
    quorom: 3
    show_all: true
classifiers:
  tfidf:
    weight: 1
    active: true
  distilbert:
    weight: 2
    active: false
